export const roomData = [
  {
    Id: 1,
    Subject: 'Board Meeting',
    Description: 'Meeting to discuss business goal of 2019.',
    StartTime: '2019, 4, 23',
    IsAllDay: true,
    EndTime: '2019, 4, 30',
    RoomId: 5,
  },
  {
    Id: 2,
    Subject: 'Training session on JSP',
    Description: 'Knowledge sharing on JSP topics.',
    StartTime: '2019, 4, 17',
    IsAllDay: true,
    EndTime: '2019, 4, 20',
    RoomId: 5,
  },
  {
    Id: 3,
    Subject: 'Sprint Planning with Team members',
    Description: 'Planning tasks for sprint.',
    StartTime: '2019, 4, 5',
    IsAllDay: true,
    EndTime: '2019, 4, 10',
    RoomId: 7,
  },
  {
    Id: 4,
    Subject: 'Meeting with Client',
    Description: 'Customer meeting to discuss features.',
    StartTime: '2019, 4, 15',
    IsAllDay: true,
    EndTime: '2019, 4, 20',
    RoomId: 8,
  },
  {
    Id: 5,
    Subject: 'Support Meeting with Managers',
    Description: 'Meeting to discuss support plan.',
    StartTime: '2019, 4, 2',
    IsAllDay: true,
    EndTime: '2019, 4, 7',
    RoomId: 5,
  },
  {
    Id: 3,
    Subject: 'Client Meeting',
    Description: 'Meeting to discuss client requirements.',
    StartTime: '2019, 4, 8',
    IsAllDay: true,
    EndTime: '2019, 4, 10',
    RoomId: 6,
  },
  {
    Id: 7,
    Subject: 'Appraisal Meeting',
    Description: 'Meeting to discuss employee appraisals.',
    StartTime: '2019, 4, 5',
    IsAllDay: true,
    EndTime: '2019, 4, 10',
    RoomId: 10,
  },
  {
    Id: 8,
    Subject: 'HR Meeting',
    Description: 'Meeting to discuss HR plans.',
    StartTime: '2019, 4, 12',
    IsAllDay: true,
    EndTime: '2019, 4, 15',
    RoomId: 4,
  },
  {
    Id: 9,
    Subject: 'Customer Meeting',
    Description: 'Meeting to discuss customer reported issues.',
    StartTime: '2019, 4, 3',
    IsAllDay: true,
    EndTime: '2019, 4, 7',
    RoomId: 8,
  },
  {
    Id: 10,
    Subject: 'Board Meeting',
    Description: 'Meeting to discuss business plans.',
    StartTime: '2019, 4, 6',
    IsAllDay: true,
    EndTime: '2019, 4, 10',
    RoomId: 9,
  },
];
